services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    working_dir: /app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
